<?php

/**
 * Translatable errors that may be returned or used as exception messages.
 */

namespace OCA\Collaboration\AppInfo;

class InvitationError
{
    public const CREATE_INVITATION_NO_RECIPIENT_EMAIL = "CREATE_INVITATION_NO_RECIPIENT_EMAIL";
    public const CREATE_INVITATION_NO_RECIPIENT_NAME = "CREATE_INVITATION_NO_RECIPIENT_NAME";
    public const CREATE_INVITATION_NO_SENDER_NAME = "CREATE_INVITATION_NO_SENDER_NAME";
    public const CREATE_INVITATION_EMAIL_INVALID = "CREATE_INVITATION_EMAIL_INVALID";
    public const CREATE_INVITATION_ERROR_SENDER_EMAIL_MISSING = "CREATE_INVITATION_ERROR_SENDER_EMAIL_MISSING";
    public const CREATE_INVITATION_EMAIL_IS_OWN_EMAIL = "CREATE_INVITATION_EMAIL_IS_OWN_EMAIL";
    public const CREATE_INVITATION_EXISTS = "CREATE_INVITATION_EXISTS";
    public const INVITATION_NOT_FOUND = "INVITATION_NOT_FOUND";
    public const CREATE_INVITATION_ERROR = "CREATE_INVITATION_ERROR";
    public const HANDLE_INVITE_ERROR = 'HANDLE_INVITE_ERROR';
    public const HANDLE_INVITE_MISSING_TOKEN = 'HANDLE_INVITE_MISSING_TOKEN';
}
