FROM nextcloud:29.0.1 as builder

ARG BRANCH

RUN apt update \
    && apt install -y git make nano

# it needs the certs from all mesh hosts
COPY nc-1/nc-1.nl/certs/cert.pem /usr/share/ca-certificates/rd-mesh/nc-1.pem
RUN echo 'rd-mesh/nc-1.pem' >> /etc/ca-certificates.conf \
     && update-ca-certificates \
    && export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

# Add the Invitation app from repository
RUN mkdir -p /tmp/invitation \
    && git clone -b ${BRANCH} https://github.com/sara-nl/nc-invitation.git /tmp/invitation
# Add test run requirements: test data, test controller, test routes
RUN cp /tmp/invitation/tests/docker/integration-tests/Version20240209130007.php /tmp/invitation/lib/Migration \
    && cp /tmp/invitation/tests/docker/integration-tests/OcsController.php /tmp/invitation/lib/Controller \
    && mv /tmp/invitation/appinfo/routes.php /tmp/invitation/appinfo/app-routes.php \
    && cp /tmp/invitation/tests/docker/integration-tests/routes.php /tmp/invitation/appinfo/routes.php

# add pre install script and make invitation app
RUN cp -R /tmp/invitation/tests/docker/nc-1/before-starting.sh /docker-entrypoint-hooks.d/before-starting
RUN chown -R www-data /docker-entrypoint-hooks.d/before-starting \
    && chmod u+x /docker-entrypoint-hooks.d/before-starting/before-starting.sh \
    && cd /tmp/invitation \
    && make -e version=test buildapp-tests \
    && chown -R www-data /tmp/invitation

USER www-data

ENV DEBUG=true