ARG FROM_IMAGE=must_be_set_in_env_file

FROM ${FROM_IMAGE} AS builder

RUN apt update \
    && apt install -y git make nano

# it needs the certs from all mesh hosts
COPY tests/docker/nc-1/nc-1.nl/certs/cert.pem /usr/share/ca-certificates/rd-mesh/nc-1.pem
RUN echo 'rd-mesh/nc-1.pem' >> /etc/ca-certificates.conf \
    && update-ca-certificates \
    && export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

# Add the Collaboration app from local source
RUN mkdir -p /tmp/collaboration
COPY . /tmp/collaboration

# Add test run requirements: test data, test controller, test routes, repair steps
RUN cp /tmp/collaboration/tests/docker/integration-tests/data/nc-1/TestData.php /tmp/collaboration/lib/Migration \
    && cp /tmp/collaboration/tests/docker/integration-tests/OcsController.php /tmp/collaboration/lib/Controller \
    && mv /tmp/collaboration/appinfo/routes.php /tmp/collaboration/appinfo/app-routes.php \
    && cp /tmp/collaboration/tests/docker/integration-tests/routes.php /tmp/collaboration/appinfo/routes.php \
    && sed -i "/^<\/info>/i <repair-steps><install><step>OCA\\\\Collaboration\\\\Migration\\\\TestData</step></install></repair-steps>" /tmp/collaboration/appinfo/info.xml

# add pre install script and make Collaboration app
RUN cp -R /tmp/collaboration/tests/docker/nc-1/before-starting.sh /docker-entrypoint-hooks.d/before-starting
RUN chown -R www-data /docker-entrypoint-hooks.d/before-starting \
    && chmod u+x /docker-entrypoint-hooks.d/before-starting/before-starting.sh \
    && cd /tmp/collaboration \
    && make -e version=test buildapp-tests

USER www-data

ENV DEBUG=true